<?xml version="1.0"?>

<robot name="mobile_robot" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find mr_ramingo)/urdf/mr_base_macro.xacro" /> 
  <!--xacro:include filename="$(find mr_ramingo)/urdf/lidar_camera_gazebo.xacro" /--> 
  <xacro:include filename="$(find mr_ramingo)/urdf/lidar.xacro"/>

	<link name="camera_link">
		<!--
    <collision>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>
		-->
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.01 0.02 0.02"/>
      </geometry>
      <material name="orange"/>
    </visual>
		<!--
    <inertial>
      <origin xyz="0 0 1" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
		-->
  </link>

	<joint name="camera_joint" type="fixed">
		<parent link="base_link" />
		<child link="camera_link" />
		<origin xyz="0.11 0.0 0.0" rpy="0 0 0"/>
	</joint>

  <!-- Differential drive controller  -->
  <gazebo>
    <plugin name="mr_ramingo_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <legacyMode>true</legacyMode>
      <rosDebugLevel>Debug</rosDebugLevel>
      <publishWheelTF>false</publishWheelTF>
      <robotNamespace>/</robotNamespace>
      <publishTf>0</publishTf>
      <publishWheelJointState>false</publishWheelJointState>
      <alwaysOn>true</alwaysOn>
      <updateRate>100.0</updateRate>
      <leftJoint>left_wheel_joint</leftJoint>
      <rightJoint>right_wheel_joint</rightJoint>
      <wheelSeparation>${2*base_radius}</wheelSeparation>
      <wheelDiameter>${2*wheel_radius}</wheelDiameter>
      <broadcastTF>1</broadcastTF>
      <wheelTorque>30</wheelTorque>
      <wheelAcceleration>1.8</wheelAcceleration>
      <commandTopic>cmd_vel</commandTopic>
      <odometryFrame>odom</odometryFrame> 
      <odometryTopic>odom</odometryTopic> 
      <robotBaseFrame>base_link</robotBaseFrame>
    </plugin>
  </gazebo> 

  <xacro:mr_base />
  <xacro:lidar />
</robot>
