<?xml version="1.0"?>

<robot name="mobile_robot" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find mr_ramingo)/urdf/mr_base_macro.xacro" /> 
  <!--xacro:include filename="$(find mr_ramingo)/urdf/lidar_camera_gazebo.xacro" /--> 
  <xacro:include filename="$(find mr_ramingo)/urdf/lidar.xacro"/>
  <xacro:include filename="$(find mr_ramingo)/urdf/camera.xacro"/>

  <!-- Differential drive controller  -->
  <gazebo>
    <plugin name="mr_ramingo_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <legacyMode>true</legacyMode>
      <rosDebugLevel>Debug</rosDebugLevel>
      <publishWheelTF>false</publishWheelTF>
      <robotNamespace>/</robotNamespace>
      <publishTf>0</publishTf>
      <publishWheelJointState>false</publishWheelJointState>
      <alwaysOn>true</alwaysOn>
      <updateRate>100.0</updateRate>
      <leftJoint>left_wheel_joint</leftJoint>
      <rightJoint>right_wheel_joint</rightJoint>
      <wheelSeparation>${2*base_radius}</wheelSeparation>
      <wheelDiameter>${2*wheel_radius}</wheelDiameter>
      <broadcastTF>1</broadcastTF>
      <wheelTorque>30</wheelTorque>
      <wheelAcceleration>1.8</wheelAcceleration>
      <commandTopic>dynamixel_workbench/cmd_vel</commandTopic>
      <odometryFrame>odom</odometryFrame> 
      <odometryTopic>odom</odometryTopic> 
      <robotBaseFrame>base_link</robotBaseFrame>
    </plugin>
  </gazebo> 

  
  <xacro:camera />
  <xacro:lidar />
  <xacro:mr_base />

</robot>
